spring:
   application:
      name: "help-desk-backend"
   datasource:
      url: jdbc:mysql://localhost:3306/helpdesk
      username: root
      password: Yash321!@
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
   ai:
      openai:
         api-key: ${PERPLEXITY_API_KEY}
         base-url: https://api.perplexity.ai
         
         chat:
           completions-path: /chat/completions
      options:
          model: sonar-pro
      embedding:
        enabled: false

server:
   port: 8082


  